-- Modification de la taille des colonnes a effectuer lors de la version 1.6.5 (demander à Vincent si c'est testé)

ALTER TABLE DOSSIER_REPONSES_LINK MODIFY IDMINISTEREATTRIBUTAIRE VARCHAR2(50);
ALTER TABLE DOSSIER_REPONSES_LINK MODIFY ROUTINGTASKTYPE VARCHAR2(50);
ALTER TABLE DOSSIER_REPONSES_LINK MODIFY ETATQUESTION VARCHAR2(100);
ALTER TABLE DOSSIER_REPONSES_LINK MODIFY TYPEQUESTION VARCHAR2(100);

ALTER TABLE DOSSIER_REPONSE MODIFY IDDOCUMENTQUESTION VARCHAR2(50);
ALTER TABLE DOSSIER_REPONSE MODIFY IDDOCUMENTREPONSE VARCHAR2(50);
ALTER TABLE DOSSIER_REPONSE MODIFY IDDOSSIERLOT VARCHAR2(50);
ALTER TABLE DOSSIER_REPONSE MODIFY IDDOCUMENTFDD VARCHAR2(50);

ALTER TABLE QUESTION MODIFY ETATQUESTION VARCHAR2(100);
ALTER TABLE QUESTION MODIFY HASHCONNEXITETEXTE VARCHAR2(50);
ALTER TABLE QUESTION MODIFY HASHCONNEXITEAN VARCHAR2(50);
ALTER TABLE QUESTION MODIFY HASHCONNEXITESE VARCHAR2(50);
ALTER TABLE QUESTION MODIFY HASHCONNEXITETITRE VARCHAR2(50);
ALTER TABLE QUESTION MODIFY IDMINISTEREINTERROGE VARCHAR2(50);