CREATE TABLE "JETON_ATTRIBUTION"
   (    "ID" VARCHAR2(36) NOT NULL ENABLE,
        "DATEATTRIBUTION" TIMESTAMP (6),
        "MINATTRIBUTION" NVARCHAR2(2000),
        "TYPEATTRIBUTION" NVARCHAR2(2000),
         CONSTRAINT "JETON_ATTRIBUTION_PK" PRIMARY KEY ("ID"),
         CONSTRAINT "JETON_ATTRIBUTION_FK" FOREIGN KEY ("ID")
          REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE
   );