ALTER TABLE QUESTION ADD DATESIGNALEMENTQUESTION TIMESTAMP(6);
ALTER TABLE QUESTION ADD DATECLOTUREQUESTION TIMESTAMP(6);
ALTER TABLE QUESTION ADD DATERAPPELQUESTION TIMESTAMP(6);

ALTER TABLE REQUETECOMPLEXE ADD DATESIGNALEMENTDEBUT TIMESTAMP(6);
ALTER TABLE REQUETECOMPLEXE ADD DATESIGNALEMENTFIN TIMESTAMP(6);
