-- FOND DE DOSSIER : suppression colonne inutile
-- mise a jour du contenu des nouvelle colonnes : id des repertoires du fond de dossier

ALTER TABLE FONDDOSSIER DROP COLUMN NIVEAU_VISIBILITE;

INSERT INTO FONDDOSSIER(ID) SELECT DISTINCT H.ID FROM HIERARCHY H WHERE H.PRIMARYTYPE = 'FondDeDossier';

UPDATE FONDDOSSIER F SET (REPERTOIRE_PARLEMENT) = (
  SELECT H.ID FROM HIERARCHY H WHERE H.PARENTID = F.ID AND H.NAME LIKE 'Pi_ces destin_es au Parlement');
  
UPDATE FONDDOSSIER F SET (REPERTOIRE_MINISTERE) = (
  SELECT H.ID FROM HIERARCHY H WHERE H.PARENTID = F.ID AND H.NAME LIKE 'Pi_ces strictement r_serv_es minist_re');
  
UPDATE FONDDOSSIER F SET (REPERTOIRE_SGG) = (
  SELECT H.ID FROM HIERARCHY H WHERE H.PARENTID = F.ID AND H.NAME LIKE 'Pi_ces minist_re attributaire et SGG');
  
