-- QUESTION : Correcte mise à jour du flag hasReponse pour savoir si la réponse est publiée ou non

UPDATE QUESTION Q SET Q.HASREPONSE= 0;
COMMIT;
BEGIN
  FOR QID IN (SELECT Q.ID FROM QUESTION Q
left join DOSSIER_REPONSE D ON D.IDDOCUMENTQUESTION = Q.ID 
left join  REPONSE R ON D.IDDOCUMENTREPONSE = R.ID 
WHERE R.PAGEJOREPONSE IS NOT NULL OR R.DATEPUBLICATIONJOREPONSE IS NOT NULL)
  LOOP
    UPDATE Question Q 
    SET 
      Q.HASREPONSE = 1 
    WHERE Q.ID = QID.ID;
  END LOOP;
END;
/
COMMIT;  
