ALTER TABLE QUESTION DROP COLUMN HASHCONNEXITEAN;
ALTER TABLE QUESTION DROP COLUMN HASHCONNEXITESE;
ALTER TABLE QUESTION DROP COLUMN HASHCONNEXITETEXTE;
ALTER TABLE QUESTION DROP COLUMN HASHCONNEXITETITRE;

ALTER TABLE QUESTION ADD HASHCONNEXITEAN nvarchar2(128);
ALTER TABLE QUESTION ADD HASHCONNEXITESE nvarchar2(128);
ALTER TABLE QUESTION ADD HASHCONNEXITETEXTE nvarchar2(128);
ALTER TABLE QUESTION ADD HASHCONNEXITETITRE nvarchar2(128);

CREATE INDEX IDX_QUESTION_19 ON QUESTION (HASHCONNEXITETITRE);
CREATE INDEX IDX_QUESTION_20 ON QUESTION (HASHCONNEXITETEXTE);
CREATE INDEX IDX_QUESTION_21 ON QUESTION (HASHCONNEXITEAN);
CREATE INDEX IDX_QUESTION_22 ON QUESTION (HASHCONNEXITESE);