ALTER TABLE LISTEELIMINATION ADD "SUPPRESSION_EN_COURS" NUMBER(1,0);
ALTER TABLE LISTEELIMINATION ADD "ABANDON_EN_COURS" NUMBER(1,0);

UPDATE LISTEELIMINATION SET ABANDON_EN_COURS=0, SUPPRESSION_EN_COURS=0;

COMMIT;