-- Ajout de colonne idMinistereAttributaire et intituleMinistereAttributaire dans la table Question pour la recherche 
-- et récupération des données déjà existantes sur les autres dossiers

ALTER TABLE QUESTION ADD IDMINISTEREATTRIBUTAIRE NVARCHAR2(50);
ALTER TABLE QUESTION ADD INTITULEMINISTEREATTRIBUTAIRE NVARCHAR2(2000);

UPDATE QUESTION QU SET IDMINISTEREATTRIBUTAIRE = (SELECT MINISTEREATTRIBUTAIRECOURANT FROM DOSSIER_REPONSE DR WHERE DR.IDDOCUMENTQUESTION=QU.ID);
UPDATE QUESTION QU SET INTITULEMINISTEREATTRIBUTAIRE = (SELECT INTITULEMINISTERE FROM DOSSIER_REPONSES_LINK DRL WHERE DRL.IDMINISTEREATTRIBUTAIRE=QU.IDMINISTEREATTRIBUTAIRE AND rownum = 1);

commit;