package fr.dila.reponses.api.enumeration;

import fr.dila.reponses.api.constant.ReponsesEventConstant;
import fr.dila.ss.api.constant.SSEventConstant;
import fr.dila.st.api.constant.STEventConstant;

public enum DailyBatchEnum {
	BATCH_EVENT_COMPUTE_STATS(ReponsesEventConstant.COMPUTE_STAT_BATCH_EVENT),
    BATCH_EVENT_UNLOCK_DOSSIER(STEventConstant.UNLOCK_BATCH_EVENT),
    BATCH_EVENT_UNLOCK_ORGANIGRAMME(SSEventConstant.UNLOCK_ORGANIGRAMME_BATCH_EVENT),
    BATCH_EVENT_USER_DESACTIVATION(ReponsesEventConstant.USER_DESACTIVATION_BATCH_EVENT),
    BATCH_EVENT_DAILY_DISTRIBUTION(ReponsesEventConstant.DAILY_DISTRIBUTION_MAIL_BATCH_EVENT),
    BATCH_EVENT_DAILY_RETIRED(ReponsesEventConstant.DAILY_RETIRED_MAIL_BATCH_EVENT),
    BATCH_EVENT_DAILY_REMIND_PASSWORD(STEventConstant.SEND_DAILY_REMIND_CHANGE_PASS_EVENT),
    BATCH_EVENT_VALIDATE_CASELINK(SSEventConstant.VALIDATE_CASELINK_EVENT),
    BATCH_EVENT_ARCHIVAGE_MAIL(ReponsesEventConstant.ARCHIVAGE_MAIL_BATCH_EVENT),
    BATCH_EVENT_PURGE_JOURNAL(ReponsesEventConstant.PURGE_JOURNAL_BATCH_EVENT),
    BATCH_EVENT_ERASE_FAVORIS(ReponsesEventConstant.ERASE_FAVORIS_BATCH_EVENT),
    BATCH_EVENT_SEND_ALERT(SSEventConstant.SEND_ALERT_BATCH_EVENT),
    BATCH_EVENT_CLEAN_DELETED_DL(SSEventConstant.CLEAN_DELETED_DL_EVENT),
    BATCH_EVENT_CLEAN_DELETED_STEP(SSEventConstant.CLEAN_DELETED_STEP_EVENT),
    BATCH_EVENT_COMPUTE_PRECOMPTAGE(ReponsesEventConstant.COMPUTE_PRECOMPTAGE_BATCH_EVENT),
    BATCH_EVENT_USER_DELETION(SSEventConstant.USER_DELETION_BATCH_EVENT),
    BATCH_EVENT_CLOSE_USERS_CONNECTIONS(SSEventConstant.BATCH_EVENT_CLOSE_USERS_CONNECTIONS),
    BATCH_EVENT_CLEAN_DELETED_REQUETE(SSEventConstant.CLEAN_DELETED_REQUETE_EVENT),
    BATCH_EVENT_CLEAN_DELETED_ALERT(SSEventConstant.CLEAN_DELETED_ALERT_EVENT),
    BATCH_EVENT_CLEAN_DELETED_FDD_FILE(SSEventConstant.CLEAN_DELETED_FDD_FILE_EVENT),
    BATCH_EVENT_CLEAN_EXPORT_STAT(ReponsesEventConstant.CLEAN_EXPORT_STAT_BATCH_EVENT),
    BATCH_EVENT_CLEAN_ALLOTISSEMENT(ReponsesEventConstant.CLEAN_DELETED_ALLOT_EVENT),
    BATCH_EVENT_BLOQUED_ROUTES(SSEventConstant.BLOCKED_ROUTES_ALERT_EVENT),
    BATCH_EVENT_DOSSIER_LINK_INCOHERENT(SSEventConstant.INCOHERENT_DOSSIER_LINK_EVENT);

    private String eventName;

    DailyBatchEnum(String eventName) {
        this.eventName = eventName;
    }
    
    public String getEventName() {
    	return this.eventName;
    }
}
