ALTER TABLE STATISTIQUE_ETAPE ADD ( "VALIDATIONSTATUS" NVARCHAR2(2000) );
ALTER TABLE STATISTIQUE_ETAPE ADD ( "DATESIGNALEMENTQUESTION" TIMESTAMP(6) );
ALTER TABLE V_STATISTIQUE_DATE_PARCOURS ADD ( "DATESIGNALEMENTQUESTION" TIMESTAMP(6) );

RENAME V_STATISTIQUE_DATE_PARCOURS TO STATISTIQUE_DATE_PARCOURS;
commit;