CREATE TABLE "RTSK_COMMENTS" 
   (	"ID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	"POS" NUMBER(10,0), 
	"ITEM" NVARCHAR2(100)
   );

INSERT INTO RTSK_COMMENTS(ID, ITEM)
SELECT COMMENTEDDOCID, ID FROM "COMMENT";

ALTER TABLE "COMMENT" RENAME COLUMN COMMENTEDDOCID TO PARENTCOMMENTID;