package fr.dila.reponses.ui.enums;

public enum MassActionType {
    MASSE_ACTION_AVIS_FAVORABLE,
    MASSE_ACTION_AVIS_DEFAVORABLE_ET_INSERER_TACHES,
    MASSE_ACTION_AVIS_DEFAVORABLE_ET_POURSUIVRE,
    MASSE_ACTION_NON_CONCERNE_REATTRIBUTION,
    MASSE_ACTION_NON_CONCERNE_REORIENTATION,
    MASSE_ACTION_NON_CONCERNE_REAFFECTATION,
    MASSE_ACTION_DEMANDE_ARBITRAGE_SGG,
    MASSE_ACTION_NON_CONCERNE_REATTRIBUTION_PLAN_CLASSEMENT,
    MASSE_ACTION_MODIFICATION_MINISTERE_RATTACHEMENT,
    MASSE_ACTION_MODIFICATION_DIRECTION_PILOTE,
    MASSE_ACTION_REATTRIBUTION_DIRECTE
}
