package fr.dila.reponses.ui.enums;

import fr.dila.st.ui.enums.ActionCategory;

public enum ReponsesActionCategory implements ActionCategory {
    ALERTE_ACTIONS,
    ALLOTISSEMENT_ACTIONS,
    CORBEILLE_DOSSIERS_ACTIONS_GENERAL,
    CORBEILLE_DOSSIERS_ACTIONS_NOTE,
    DELEGATION_CONSULTATION_ACTIONS,
    DELEGATION_CREATION_ACTIONS,
    DELEGATION_MODIFICATION_ACTIONS,
    DOSSIERS_MASS_ACTIONS_DIVERS,
    DOSSIERS_MASS_ACTIONS_EDITION,
    DOSSIERS_MASS_ACTIONS_FDR,
    DOSSIERS_MASS_ACTIONS_RENVOIS,
    DOSSIER_CONNEXE_ACTIONS,
    DOSSIER_CONNEXE_RETOUR_ACTIONS,
    DOSSIER_CONNEXE_RETOUR_MINISTERE_ACTIONS,
    DOSSIER_CONNEXE_RETOUR_QUESTION_COPIE,
    FAVORI_TRAVAIL_DOSSIERS_ACTIONS,
    LISTE_ELIMINATION_ACTIONS,
    LISTE_ELIMINATION_CONSULTATION_LIST,
    PLAN_CLASSEMENT_DOSSIERS_ACTIONS_GENERAL,
    RECHERCHE_DOSSIER_ACTIONS_GENERAL,
    REQUETE_PERSO_ACTIONS;

    @Override
    public String getName() {
        return name();
    }
}
