-- le demarrage de l'application va ajouter les colonnes
-- IDDOCUMENTQUESTION, IDDOCUMENTREPONSES, et IDDOCUMENTFDD 
-- a la table DOSSIER_REPONSE
-- la commande suivante va recopier les donnees du schema
-- parapheur vers le dossier_reponse

UPDATE DOSSIER_REPONSE D SET (IDDOCUMENTQUESTION, IDDOCUMENTREPONSE) = (
  SELECT P.IDDOCUMENTQUESTION, P.IDDOCUMENTREPONSE FROM
  PARAPHEUR_REPONSE P, HIERARCHY H WHERE P.ID = H.ID AND H.PARENTID = D.ID ) WHERE D.ID IS NOT NULL;

UPDATE DOSSIER_REPONSE D SET (IDDOCUMENTFDD) = (
  SELECT H.ID FROM HIERARCHY H WHERE H.PRIMARYTYPE IN ('FondDeDossier') AND H.PARENTID = D.ID) WHERE D.ID IS NOT NULL;