-- la commande suivante va dimensionner les colonnes ERRATUM et TEXT_CONSOLIDE en NCLOB

-- Passage du type de l'erratum à un type plus large
ALTER TABLE ERRATUM#ANONYMOUSTYPE ADD TMP_TEXTE_CONSOLIDE NCLOB;
UPDATE ERRATUM#ANONYMOUSTYPE SET TMP_TEXTE_CONSOLIDE=TEXTE_CONSOLIDE;
ALTER TABLE ERRATUM#ANONYMOUSTYPE DROP COLUMN TEXTE_CONSOLIDE;
ALTER TABLE ERRATUM#ANONYMOUSTYPE RENAME COLUMN TMP_TEXTE_CONSOLIDE to TEXTE_CONSOLIDE;

ALTER TABLE REPONSE ADD TMP_ERRATUM NCLOB;
UPDATE REPONSE SET TMP_ERRATUM=ERRATUM;
ALTER TABLE REPONSE DROP COLUMN ERRATUM;
ALTER TABLE REPONSE RENAME COLUMN TMP_ERRATUM to ERRATUM;