ALTER TABLE DOSSIER_REPONSE RENAME COLUMN CANDIDATARCHIVAGE TO LISTEELIMINATION;
update DOSSIER_REPONSE set LISTEELIMINATION=null;
ALTER TABLE DOSSIER_REPONSE MODIFY LISTEELIMINATION VARCHAR2(50);

CREATE TABLE "LISTEELIMINATION"
  (
    "ID" VARCHAR2(36) NOT NULL ENABLE,
    "EN_COURS" NUMBER(1,0),
    CONSTRAINT "LISTEELIMINATION_PK" PRIMARY KEY ("ID"),
    CONSTRAINT "LIST_3B07BA5B_FK" FOREIGN KEY ("ID")
     REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE
  );