  CREATE INDEX "IDX_QUESTION_16" ON "QUESTION" ("HASHCONNEXITETITRE");
  
  CREATE INDEX "IDX_QUESTION_17" ON "QUESTION" ("HASHCONNEXITETEXTE");
  
  CREATE INDEX "IDX_QUESTION_18" ON "QUESTION" ("HASHCONNEXITEAN");
  
  CREATE INDEX "IDX_QUESTION_19" ON "QUESTION" ("HASHCONNEXITESE");
  