DROP TABLE "STATISTIQUE_ETAPE";    
  CREATE TABLE "STATISTIQUE_ETAPE"
   (          
    "DATEJO" TIMESTAMP (6),
                "NUMERO" NUMBER(19,0),
                "ORIGINE" NVARCHAR2(50),
                "AUTEUR" NVARCHAR2(201),
                "IDMINISTERE" VARCHAR2(255 BYTE),
                "MINISTERE" NVARCHAR2(2000),
                "IDDIRECTION" NVARCHAR2(50),
                "DIRECTION" NVARCHAR2(2000),
                "DATEJOREPONSE" TIMESTAMP (6),
                "IDTYPE" NVARCHAR2(2000),
                "TYPE" VARCHAR2(255 BYTE),
                "POSTE" NVARCHAR2(2000),
                "IDMAILBOX" VARCHAR2(255 BYTE),
                "DATEDEBUT" TIMESTAMP (6),
                "DATEFIN" TIMESTAMP (6),
                "REPONDU" NUMBER(1,0),
                "IDMINISTEREETAPE" VARCHAR2(2000 BYTE),
                "IDMINISTERERATTACHEMENT" VARCHAR2(255),
                "INTITULEMINISTERERATTACHEMENT" NVARCHAR2(2000),
                "VALIDATIONSTATUS" NVARCHAR2(2000),
                "DATESIGNALEMENTQUESTION" TIMESTAMP (6),
                "EDITION" NVARCHAR2(2000),
                "EDITIONMINISTERERATTACHEMENT" NVARCHAR2(2000)
   )  ;

ALTER TABLE STATISTIQUE_DATE_PARCOURS ADD EDITION NVARCHAR2(2000);
COMMIT;
