-- Création
CREATE TABLE "INFO_UTILISATEUR_CONNECTION" 
   (	"ID" VARCHAR2(36 BYTE), 
	"USERNAME" NVARCHAR2(2000), 
	"ISLOGOUT" NUMBER(1,0), 
	"FIRSTNAME" NVARCHAR2(2000), 
	"DATECONNECTION" TIMESTAMP (6), 
	"LASTNAME" NVARCHAR2(2000)
   ) ;


-- Contraintes
ALTER TABLE "INFO_UTILISATEUR_CONNECTION" ADD CONSTRAINT "INFO_UTILISATEUR_CONNECTION_PK" PRIMARY KEY ("ID") ENABLE;
 
ALTER TABLE "INFO_UTILISATEUR_CONNECTION" MODIFY ("ID" NOT NULL ENABLE);

ALTER TABLE "INFO_UTILISATEUR_CONNECTION" ADD CONSTRAINT "INFO_B4B11272_FK" FOREIGN KEY ("ID")
	  REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE;


-- Index

CREATE UNIQUE INDEX "IDX_INFO_UTIL_CONNECT_ISLOGOUT" ON "INFO_UTILISATEUR_CONNECTION" ("ISLOGOUT", "ID");

CREATE UNIQUE INDEX "IDX_INFO_UTIL_CONNECT_USERNAME" ON "INFO_UTILISATEUR_CONNECTION" ("USERNAME", "ID");

commit;
