-- Mise à jour schema table jeton_doc
ALTER TABLE "JETON_DOC" ADD "DATE_ATTRIBUTION" TIMESTAMP(6);
ALTER TABLE "JETON_DOC" ADD "MIN_ATTRIBUTION" NVARCHAR2(2000);
ALTER TABLE "JETON_DOC" ADD "TYPE_ATTRIBUTION" NVARCHAR2(2000);
-- Mise à jour données jeton_doc
UPDATE "JETON_DOC" 
SET "DATE_ATTRIBUTION" = (SELECT "DATEATTRIBUTION" FROM "JETON_ATTRIBUTION" WHERE "JETON_ATTRIBUTION"."ID" = (SELECT "ID" FROM "HIERARCHY" WHERE "PARENTID" = "JETON_DOC"."ID")),
"MIN_ATTRIBUTION" = (SELECT "MINATTRIBUTION" FROM "JETON_ATTRIBUTION" WHERE "JETON_ATTRIBUTION"."ID" = (SELECT "ID" FROM "HIERARCHY" WHERE "PARENTID" = "JETON_DOC"."ID")),
"TYPE_ATTRIBUTION" = (SELECT "TYPEATTRIBUTION" FROM "JETON_ATTRIBUTION" WHERE "JETON_ATTRIBUTION"."ID" = (SELECT "ID" FROM "HIERARCHY" WHERE "PARENTID" = "JETON_DOC"."ID"));

commit;
-- Suppression table jeton_attribution
drop table "JETON_ATTRIBUTION";
commit;
/
