ALTER TABLE "DOSSIER_REPONSE" ADD "ISARBITRATED" NUMBER(1,0) DEFAULT 0;

UPDATE "DOSSIER_REPONSE" SET "ISARBITRATED"=1 WHERE "LASTDOCUMENTROUTE" IN (SELECT distinct("DOCUMENTROUTEID") FROM "ROUTING_TASK" WHERE "TYPE"='12')

commit;
