CREATE TABLE "RTSK_COMMENTS" (
	"ID" VARCHAR2(36 BYTE) NOT NULL ENABLE, 
	"POS" NUMBER(10,0), 
	"ITEM" NVARCHAR2(100)
);
   
CREATE INDEX "IDX_RTSK_COMMENTS_ID" ON "RTSK_COMMENTS" ("ID"); 

CREATE UNIQUE INDEX "IDX_RTSK_COMMENTS_ID_ITEM" ON "RTSK_COMMENTS" ("ID", "ITEM"); 

ALTER TABLE "RTSK_COMMENTS" ADD CONSTRAINT "RTSK_COMMENTS_FK" FOREIGN KEY ("ID")
	  REFERENCES "HIERARCHY" ("ID") ON DELETE CASCADE ENABLE;

INSERT INTO RTSK_COMMENTS(ID, ITEM)
SELECT COMMENTEDDOCID, ID FROM "COMMENT";

ALTER TABLE "COMMENT" RENAME COLUMN COMMENTEDDOCID TO PARENTCOMMENTID;